export const services = [
    { value: 'trail-hitcher', label: 'Trail Hitcher', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'body-cover', label: 'Body Cover', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'patriot-liner', label: 'Patriot Liner', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'suspension', label: 'Suspension', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'rust-prevention', label: 'Rust Prevention', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'ceramic-coating', label: 'Ceramic Coating', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'service7', label: 'Service7', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'service8', label: 'Service8', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'service9', label: 'Service9', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'service10', label: 'Service10', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'service11', label: 'Service11', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'service12', label: 'Service12', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
];