export const vehicleInformation = {
    makeData: [
        { value: "acura", label: "Acura" },
        { value: "alfaRomeo", label: "AlfaRomeo" },
        { value: "astonMartin", label: "AstonMartin" },
        { value: "audi", label: "Audi" },
        { value: "bmw", label: "Bmw" },
        { value: "bentley", label: "Bentley" },
        { value: "bugatti", label: "Bugatti" },
        { value: "buick", label: "Buick" },
        { value: "cadillac", label: "Cadillac" },
        { value: "chevrolet", label: "Chevrolet" },
        { value: "chrysler", label: "Chrysler" },
        { value: "dodge", label: "Dodge" },
        { value: "fiat", label: "Fiat" },
        { value: "ferrari", label: "Ferrari" },
        { value: "ford", label: "Ford" },
        { value: "genesis", label: "Genesis" },
        { value: "gmc", label: "Gmc" },
        { value: "honda", label: "Honda" },
        { value: "hummer", label: "Hummer" },
        { value: "hyundai", label: "Hyundai" },
        { value: "infiniti", label: "Infiniti" },
        { value: "isuzu", label: "Isuzu" },
        { value: "jaguar", label: "Jaguar" },
        { value: "jeep", label: "Jeep" },
        { value: "kia", label: "Kia" },
        { value: "lamborghini", label: "Lamborghini" },
        { value: "lancia", label: "Lancia" },
        { value: "landRover", label: "LandRover" },
        { value: "lexus", label: "Lexus" },
        { value: "lincoln", label: "Lincoln" },
        { value: "lotus", label: "Lotus" },
        { value: "maserati", label: "Maserati" },
        { value: "maybach", label: "Maybach" },
        { value: "mazda", label: "Mazda" },
        { value: "mclaren", label: "Mclaren" },
        { value: "mercedesBenz", label: "MercedesBenz" },
        { value: "mercury", label: "Mercury" },
        { value: "mini", label: "Mini" },
        { value: "mitsubishi", label: "Mitsubishi" },
        { value: "nissan", label: "Nissan" },
        { value: "noble", label: "Noble" },
        { value: "opel", label: "Opel" },
        { value: "pagani", label: "Pagani" },
        { value: "peugeot", label: "Peugeot" },
        { value: "plymouth", label: "Plymouth" },
        { value: "pontiac", label: "Pontiac" },
        { value: "porsche", label: "Porsche" },
        { value: "proton", label: "Proton" },
        { value: "ram", label: "Ram" },
        { value: "renault", label: "Renault" },
        { value: "rollsRoyce", label: "RollsRoyce" },
        { value: "saab", label: "Saab" },
        { value: "saleen", label: "Saleen" },
        { value: "saturn", label: "Saturn" },
        { value: "scion", label: "Scion" },
        { value: "seat", label: "Seat" },
        { value: "skoda", label: "Skoda" },
        { value: "smart", label: "Smart" },
        { value: "ssangyong", label: "Ssangyong" },
        { value: "subaru", label: "Subaru" },
        { value: "suzuki", label: "Suzuki" },
        { value: "talbot", label: "Talbot" },
        { value: "tata", label: "Tata" },
        { value: "tatra", label: "Tatra" },
        { value: "tesla", label: "Tesla" },
        { value: "toyota", label: "Toyota" },
        { value: "trabant", label: "Trabant" },
        { value: "triumph", label: "Triumph" },
        { value: "tvr", label: "Tvr" },
        { value: "vauxhall", label: "Vauxhall" },
        { value: "vector", label: "Vector" },
        { value: "venturi", label: "Venturi" },
        { value: "volkswagen", label: "Volkswagen" },
        { value: "volvo", label: "Volvo" },
        { value: "other", label: "Other" },
    ],
    // modelData: [
    //     { value: 'DB11', label: 'DB11' },
    //     { value: 'DB9', label: 'DB9' },
    //     { value: 'DBS', label: 'DBS' },
    //     { value: 'Vantage', label: 'Vantage' },
    //     { value: 'Rapide', label: 'Rapide' },
    //     { value: 'Valkyrie', label: 'Valkyrie' },
    //     { value: 'Virage', label: 'Virage' },
    //     { value: 'One-77', label: 'One-77' },
    //     { value: 'Lagonda', label: 'Lagonda' },
    //     { value: 'Cygent', label: 'Cygent' },
    // ],

    modelsData: {
        default: [
            {
                value: "make",
                label: "First, choose a car make. ",
                disabled: true,
                hidden: true,
            },
        ],
        acura: [
            { value: "cl", label: "CL" },
            { value: "ilx", label: "ILX" },
            { value: "integra", label: "Integra" },
            { value: "legend", label: "Legend" },
            { value: "mdx", label: "MDX" },
            { value: "nsx", label: "NSX" },
            { value: "rdx", label: "RDX" },
            { value: "rl", label: "RL" },
            { value: "rlx", label: "RLX" },
            { value: "rsx", label: "RSX" },
            { value: "slx", label: "SLX" },
            { value: "tl", label: "TL" },
            { value: "tlx", label: "TLX" },
            { value: "tsx", label: "TSX" },
            { value: "vigor", label: "Vigor" },
            { value: "zdx", label: "ZDX" },
        ],
        alfaRomeo: [
            { value: "4c", label: "4C" },
            { value: "giulia", label: "Giulia" },
            { value: "giulietta", label: "Giulietta" },
            { value: "stelvio", label: "Stelvio" },
            { value: "gt", label: "GT" },
            { value: "gta", label: "GTA" },
            { value: "spider", label: "Spider" },
            { value: "156", label: "156" },
            { value: "159", label: "159" },
            { value: "166", label: "166" },
            { value: "brera", label: "Brera" },
            { value: "gtv", label: "GTV" },
            { value: "mito", label: "MiTo" },
        ],
        astonMartin: [
            { value: "db11", label: "DB11" },
            { value: "db9", label: "DB9" },
            { value: "dbs", label: "DBS" },
            { value: "vantage", label: "Vantage" },
            { value: "rapide", label: "Rapide" },
            { value: "valkyrie", label: "Valkyrie" },
            { value: "virage", label: "Virage" },
            { value: "one77", label: "One-77" },
            { value: "lagonda", label: "Lagonda" },
            { value: "cygnet", label: "Cygnet" },
        ],
        audi: [
            { value: "a1", label: "A1" },
            { value: "a2", label: "A2" },
            { value: "a3", label: "A3" },
            { value: "a4", label: "A4" },
            { value: "a5", label: "A5" },
            { value: "a6", label: "A6" },
            { value: "a7", label: "A7" },
            { value: "a8", label: "A8" },
            { value: "q2", label: "Q2" },
            { value: "q3", label: "Q3" },
            { value: "q4", label: "Q4" },
            { value: "q5", label: "Q5" },
            { value: "q6", label: "Q6" },
            { value: "q7", label: "Q7" },
            { value: "q8", label: "Q8" },
            { value: "r8", label: "R8" },
            { value: "etron", label: "e-tron" },
            { value: "etronGT", label: "e-tron GT" },
            { value: "s3", label: "S3" },
            { value: "s4", label: "S4" },
            { value: "s5", label: "S5" },
            { value: "s6", label: "S6" },
            { value: "s7", label: "S7" },
            { value: "s8", label: "S8" },
            { value: "tt", label: "TT" },
        ],
        bmw: [
            { value: "1series", label: "1 Series" },
            { value: "2series", label: "2 Series" },
            { value: "3series", label: "3 Series" },
            { value: "4series", label: "4 Series" },
            { value: "5series", label: "5 Series" },
            { value: "6series", label: "6 Series" },
            { value: "7series", label: "7 Series" },
            { value: "8series", label: "8 Series" },
            { value: "i3", label: "i3" },
            { value: "i8", label: "i8" },
            { value: "m2", label: "M2" },
            { value: "m3", label: "M3" },
            { value: "m4", label: "M4" },
            { value: "m5", label: "M5" },
            { value: "m6", label: "M6" },
            { value: "x1", label: "X1" },
            { value: "x2", label: "X2" },
            { value: "x3", label: "X3" },
            { value: "x4", label: "X4" },
            { value: "x5", label: "X5" },
            { value: "x6", label: "X6" },
            { value: "x7", label: "X7" },
            { value: "x8", label: "X8" },
            { value: "z3", label: "Z3" },
            { value: "z4", label: "Z4" },
            { value: "z8", label: "Z8" },
        ],
        bentley: [
            { value: "arnage", label: "Arnage" },
            { value: "azure", label: "Azure" },
            { value: "bentayga", label: "Bentayga" },
            { value: "brooklands", label: "Brooklands" },
            { value: "continentalFlyingSpur", label: "Continental Flying Spur" },
            { value: "continentalGT", label: "Continental GT" },
            { value: "continentalSupersports", label: "Continental Supersports" },
            { value: "mulsanne", label: "Mulsanne" },
        ],
        bugatti: [
            { value: "centodieci", label: "Centodieci" },
            { value: "chiron", label: "Chiron" },
            { value: "divo", label: "Divo" },
            { value: "eb110", label: "EB110" },
            { value: "veyron", label: "Veyron" },
        ],
        buick: [
            { value: "century", label: "Century" },
            { value: "electra", label: "Electra" },
            { value: "enclave", label: "Enclave" },
            { value: "encore", label: "Encore" },
            { value: "encoreGX", label: "Encore GX" },
            { value: "envision", label: "Envision" },
            { value: "lacrosse", label: "LaCrosse" },
            { value: "lesabre", label: "LeSabre" },
            { value: "lucerne", label: "Lucerne" },
            { value: "parkAvenue", label: "Park Avenue" },
            { value: "rainier", label: "Rainier" },
            { value: "reatta", label: "Reatta" },
            { value: "regal", label: "Regal" },
            { value: "rendezvous", label: "Rendezvous" },
            { value: "riviera", label: "Riviera" },
            { value: "skylark", label: "Skylark" },
            { value: "terraza", label: "Terraza" },
            { value: "verano", label: "Verano" },
        ],
        cadillac: [
            { value: "ats", label: "ATS" },
            { value: "atsV", label: "ATS-V" },
            { value: "ct4", label: "CT4" },
            { value: "ct5", label: "CT5" },
            { value: "ct6", label: "CT6" },
            { value: "cts", label: "CTS" },
            { value: "ctsV", label: "CTS-V" },
            { value: "escalade", label: "Escalade" },
            { value: "escaladeESV", label: "Escalade ESV" },
            { value: "seville", label: "Seville" },
            { value: "srx", label: "SRX" },
            { value: "sts", label: "STS" },
            { value: "xt4", label: "XT4" },
            { value: "xt5", label: "XT5" },
            { value: "xt6", label: "XT6" },
            { value: "xts", label: "XTS" },
        ],
        chevrolet: [
            { value: "astro", label: "Astro" },
            { value: "avalanche", label: "Avalanche" },
            { value: "aveo", label: "Aveo" },
            { value: "belAir", label: "Bel Air" },
            { value: "beretta", label: "Beretta" },
            { value: "blazer", label: "Blazer" },
            { value: "boltEV", label: "Bolt EV" },
            { value: "camaro", label: "Camaro" },
            { value: "caprice", label: "Caprice" },
            { value: "captivaSport", label: "Captiva Sport" },
            { value: "cavalier", label: "Cavalier" },
            { value: "celebrity", label: "Celebrity" },
            { value: "chevelle", label: "Chevelle" },
            { value: "chevette", label: "Chevette" },
            { value: "citation", label: "Citation" },
            { value: "cityExpress", label: "City Express" },
            { value: "classic", label: "Classic" },
            { value: "cobalt", label: "Cobalt" },
            { value: "colorado", label: "Colorado" },
            { value: "corvette", label: "Corvette" },
            { value: "cruze", label: "Cruze" },
            { value: "elCamino", label: "El Camino" },
            { value: "equinox", label: "Equinox" },
            { value: "express", label: "Express" },
            { value: "gseries", label: "G-Series" },
            { value: "hhr", label: "HHR" },
            { value: "impala", label: "Impala" },
            { value: "kodiak", label: "Kodiak" },
            { value: "lumina", label: "Lumina" },
            { value: "malibu", label: "Malibu" },
            { value: "malibuMaxx", label: "Malibu Maxx" },
            { value: "metro", label: "Metro" },
            { value: "monteCarlo", label: "Monte Carlo" },
            { value: "nova", label: "Nova" },
            { value: "prizm", label: "Prizm" },
            { value: "s10", label: "S10" },
            { value: "silverado", label: "Silverado" },
            { value: "sonic", label: "Sonic" },
            { value: "spark", label: "Spark" },
            { value: "ss", label: "SS" },
            { value: "ssr", label: "SSR" },
            { value: "suburban", label: "Suburban" },
            { value: "tahoe", label: "Tahoe" },
            { value: "tracker", label: "Tracker" },
            { value: "trailblazer", label: "Trailblazer" },
            { value: "traverse", label: "Traverse" },
            { value: "trax", label: "Trax" },
            { value: "uplander", label: "Uplander" },
            { value: "venture", label: "Venture" },
            { value: "volt", label: "Volt" },
        ],
        chrysler: [
            { value: "200", label: "200" },
            { value: "300", label: "300" },
            { value: "300M", label: "300M" },
            { value: "aspen", label: "Aspen" },
            { value: "concorde", label: "Concorde" },
            { value: "cordoba", label: "Cordoba" },
            { value: "crossfire", label: "Crossfire" },
            { value: "fifthAvenue", label: "Fifth Avenue" },
            { value: "imperial", label: "Imperial" },
            { value: "lhs", label: "LHS" },
            { value: "newYorker", label: "New Yorker" },
            { value: "pacificaN", label: "Pacifica (N)" },
            { value: "pacificaN", label: "Pacifica (N)" },
            { value: "prowler", label: "Prowler" },
            { value: "ptCruiser", label: "PT Cruiser" },
            { value: "sebring", label: "Sebring" },
            { value: "tc", label: "TC" },
            { value: "townAndCountry", label: "Town & Country" },
            { value: "voyager", label: "Voyager" },
        ],
        dodge: [
            { value: "avenger", label: "Avenger" },
            { value: "caliber", label: "Caliber" },
            { value: "caravan", label: "Caravan" },
            { value: "challenger", label: "Challenger" },
            { value: "charger", label: "Charger" },
            { value: "colt", label: "Colt" },
            { value: "dakota", label: "Dakota" },
            { value: "dart", label: "Dart" },
            { value: "daytona", label: "Daytona" },
            { value: "demon", label: "Demon" },
            { value: "durango", label: "Durango" },
            { value: "grandCaravan", label: "Grand Caravan" },
            { value: "intrepid", label: "Intrepid" },
            { value: "journey", label: "Journey" },
            { value: "magnum", label: "Magnum" },
            { value: "neon", label: "Neon" },
            { value: "nitro", label: "Nitro" },
            { value: "omni", label: "Omni" },
            { value: "ram", label: "Ram" },
            { value: "ramVan", label: "Ram Van" },
            { value: "ramWagon", label: "Ram Wagon" },
            { value: "shadow", label: "Shadow" },
            { value: "spirit", label: "Spirit" },
            { value: "sprinter", label: "Sprinter" },
            { value: "stealth", label: "Stealth" },
            { value: "stratus", label: "Stratus" },
            { value: "viper", label: "Viper" },
        ],

        fiat: [
            { value: "124Spider", label: "124 Spider" },
            { value: "500", label: "500" },
            { value: "500L", label: "500L" },
            { value: "500X", label: "500X" },
            { value: "barchetta", label: "Barchetta" },
            { value: "brava", label: "Brava" },
            { value: "bravo", label: "Bravo" },
            { value: "cinquecento", label: "Cinquecento" },
            { value: "coupe", label: "Coupe" },
            { value: "croma", label: "Croma" },
            { value: "doblo", label: "Doblo" },
            { value: "ducato", label: "Ducato" },
            { value: "fiorino", label: "Fiorino" },
            { value: "freemont", label: "Freemont" },
            { value: "idea", label: "Idea" },
            { value: "marea", label: "Marea" },
            { value: "multipla", label: "Multipla" },
            { value: "palio", label: "Palio" },
            { value: "panda", label: "Panda" },
            { value: "punto", label: "Punto" },
            { value: "qubo", label: "Qubo" },
            { value: "scudo", label: "Scudo" },
            { value: "sedici", label: "Sedici" },
            { value: "seicento", label: "Seicento" },
            { value: "stilo", label: "Stilo" },
            { value: "talento", label: "Talento" },
            { value: "tipo", label: "Tipo" },
            { value: "ulysse", label: "Ulysse" },
            { value: "uno", label: "Uno" },
            { value: "x1-9", label: "X1/9" },
        ],
        ferrari: [
            { value: "250GT", label: "250 GT" },
            { value: "288GTO", label: "288 GTO" },
            { value: "308GTB", label: "308 GTB" },
            { value: "308GTS", label: "308 GTS" },
            { value: "328GTB", label: "328 GTB" },
            { value: "328GTS", label: "328 GTS" },
            { value: "348", label: "348" },
            { value: "348Spider", label: "348 Spider" },
            { value: "348TB", label: "348 TB" },
            { value: "348TS", label: "348 TS" },
            { value: "360", label: "360" },
            { value: "360Spider", label: "360 Spider" },
            { value: "456GT", label: "456 GT" },
            { value: "456MGT", label: "456M GT" },
            { value: "458Italia", label: "458 Italia" },
            { value: "458Spider", label: "458 Spider" },
            { value: "488GTB", label: "488 GTB" },
            { value: "488Spider", label: "488 Spider" },
            { value: "512TR", label: "512 TR" },
            { value: "550Maranello", label: "550 Maranello" },
            { value: "575M", label: "575M" },
            { value: "599GTB", label: "599 GTB" },
            { value: "599GTO", label: "599 GTO" },
            { value: "612Scaglietti", label: "612 Scaglietti" },
            { value: "812Superfast", label: "812 Superfast" },
            { value: "california", label: "California" },
            { value: "californiaT", label: "California T" },
            { value: "daytona", label: "Daytona" },
            { value: "enzo", label: "Enzo" },
            { value: "f12berlinetta", label: "F12berlinetta" },
            { value: "f355", label: "F355" },
            { value: "f40", label: "F40" },
            { value: "f430", label: "F430" },
            { value: "f50", label: "F50" },
            { value: "f512m", label: "F512M" },
            { value: "f8tributo", label: "F8 Tributo" },
            { value: "f8spider", label: "F8 Spider" },
            { value: "ff", label: "FF" },
            { value: "gto", label: "GTO" },
            { value: "laFerrari", label: "LaFerrari" },
            { value: "mondial", label: "Mondial" },
            { value: "portofino", label: "Portofino" },
            { value: "testarossa", label: "Testarossa" },
        ],
        ford: [
            { value: "aerostar", label: "Aerostar" },
            { value: "aspire", label: "Aspire" },
            { value: "bronco", label: "Bronco" },
            { value: "broncoSport", label: "Bronco Sport" },
            { value: "cmax", label: "C-Max" },
            { value: "contour", label: "Contour" },
            { value: "crownVictoria", label: "Crown Victoria" },
            { value: "econoline", label: "Econoline" },
            { value: "ecosport", label: "EcoSport" },
            { value: "edge", label: "Edge" },
            { value: "escape", label: "Escape" },
            { value: "escort", label: "Escort" },
            { value: "excursion", label: "Excursion" },
            { value: "expedition", label: "Expedition" },
            { value: "explorer", label: "Explorer" },
            { value: "f100", label: "F-100" },
            { value: "f150", label: "F-150" },
            { value: "f250", label: "F-250" },
            { value: "f350", label: "F-350" },
            { value: "f450", label: "F-450" },
            { value: "f550", label: "F-550" },
            { value: "fairlane", label: "Fairlane" },
            { value: "falcon", label: "Falcon" },
            { value: "festiva", label: "Festiva" },
            { value: "fiesta", label: "Fiesta" },
            { value: "fiveHundred", label: "Five Hundred" },
            { value: "flex", label: "Flex" },
            { value: "focus", label: "Focus" },
            { value: "freestar", label: "Freestar" },
            { value: "freestyle", label: "Freestyle" },
            { value: "fusion", label: "Fusion" },
            { value: "fusionEnergi", label: "Fusion Energi" },
            { value: "fusionHybrid", label: "Fusion Hybrid" },
            { value: "galaxie", label: "Galaxie" },
            { value: "granada", label: "Granada" },
            { value: "gt", label: "GT" },
            { value: "ltd", label: "LTD" },
            { value: "maverick", label: "Maverick" },
            { value: "modelA", label: "Model A" },
            { value: "modelT", label: "Model T" },
            { value: "mustang", label: "Mustang" },
            { value: "pinto", label: "Pinto" },
            { value: "probe", label: "Probe" },
            { value: "ranchero", label: "Ranchero" },
            { value: "ranger", label: "Ranger" },
            { value: "taunus", label: "Taunus" },
            { value: "taurus", label: "Taurus" },
            { value: "thunderbird", label: "Thunderbird" },
            { value: "torino", label: "Torino" },
            { value: "transit", label: "Transit" },
            { value: "transitConnect", label: "Transit Connect" },
            { value: "windstar", label: "Windstar" },
        ],
        genesis: [
            { value: "g70", label: "G70" },
            { value: "g80", label: "G80" },
            { value: "g90", label: "G90" },
            { value: "gv70", label: "GV70" },
            { value: "gv80", label: "GV80" },
            { value: "gv90", label: "GV90" },
        ],
        gmc: [
            { value: "acadia", label: "Acadia" },
            { value: "canyon", label: "Canyon" },
            { value: "envoy", label: "Envoy" },
            { value: "envoyXL", label: "Envoy XL" },
            { value: "envoyXUV", label: "Envoy XUV" },
            { value: "jimmy", label: "Jimmy" },
            { value: "rallyWagon", label: "Rally Wagon" },
            { value: "safari", label: "Safari" },
            { value: "savana", label: "Savana" },
            { value: "sierra", label: "Sierra" },
            { value: "sierra1500", label: "Sierra 1500" },
            { value: "sierra2500HD", label: "Sierra 2500HD" },
            { value: "sierra3500", label: "Sierra 3500" },
            { value: "sierra3500HD", label: "Sierra 3500HD" },
            { value: "terrain", label: "Terrain" },
            { value: "typhoon", label: "Typhoon" },
            { value: "yukon", label: "Yukon" },
            { value: "yukonXL", label: "Yukon XL" },
        ],
        honda: [
            { value: "accord", label: "Accord" },
            { value: "civic", label: "Civic" },
            { value: "clarity", label: "Clarity" },
            { value: "crv", label: "CR-V" },
            { value: "crz", label: "CR-Z" },
            { value: "element", label: "Element" },
            { value: "fit", label: "Fit" },
            { value: "hrv", label: "HR-V" },
            { value: "insight", label: "Insight" },
            { value: "odyssey", label: "Odyssey" },
            { value: "passport", label: "Passport" },
            { value: "pilot", label: "Pilot" },
            { value: "prelude", label: "Prelude" },
            { value: "ridgeline", label: "Ridgeline" },
            { value: "s2000", label: "S2000" },
            { value: "stepwgn", label: "Stepwgn" },
            { value: "vamos", label: "Vamos" },
        ],
        hummer: [
            { value: "h1", label: "H1" },
            { value: "h2", label: "H2" },
            { value: "h3", label: "H3" },
        ],
        hyundai: [
            { value: "accent", label: "Accent" },
            { value: "atostar", label: "Atos Prime" },
            { value: "azera", label: "Azera" },
            { value: "elantra", label: "Elantra" },
            { value: "entourage", label: "Entourage" },
            { value: "equus", label: "Equus" },
            { value: "genesis", label: "Genesis" },
            { value: "genesisCoupe", label: "Genesis Coupe" },
            { value: "getz", label: "Getz" },
            { value: "grandeur", label: "Grandeur" },
            { value: "h1", label: "H-1" },
            { value: "ioniq", label: "Ioniq" },
            { value: "ix20", label: "ix20" },
            { value: "ix35", label: "ix35" },
            { value: "kona", label: "Kona" },
            { value: "lantra", label: "Lantra" },
            { value: "lavita", label: "Lavita" },
            { value: "matrix", label: "Matrix" },
            { value: "n2025", label: "N 2025" },
            { value: "nexo", label: "Nexo" },
            { value: "pavise", label: "Pavise" },
            { value: "santaFe", label: "Santa Fe" },
            { value: "sonata", label: "Sonata" },
            { value: "sonica", label: "Sonica" },
            { value: "tucson", label: "Tucson" },
            { value: "veloster", label: "Veloster" },
            { value: "venue", label: "Venue" },
            { value: "veracruz", label: "Veracruz" },
            { value: "volester", label: "Volester" },
            { value: "xcent", label: "Xcent" },
        ],
        infiniti: [
            { value: "ex", label: "EX" },
            { value: "fx", label: "FX" },
            { value: "g", label: "G" },
            { value: "i30", label: "i30" },
            { value: "j30", label: "J30" },
            { value: "m", label: "M" },
            { value: "q30", label: "Q30" },
            { value: "q45", label: "Q45" },
            { value: "q50", label: "Q50" },
            { value: "q60", label: "Q60" },
            { value: "q70", label: "Q70" },
            { value: "qx30", label: "QX30" },
            { value: "qx4", label: "QX4" },
            { value: "qx50", label: "QX50" },
            { value: "qx56", label: "QX56" },
            { value: "qx60", label: "QX60" },
            { value: "qx70", label: "QX70" },
            { value: "qx80", label: "QX80" },
        ],
        isuzu: [
            { value: "amigo", label: "Amigo" },
            { value: "ascender", label: "Ascender" },
            { value: "axiom", label: "Axiom" },
            { value: "gemini", label: "Gemini" },
            { value: "hombre", label: "Hombre" },
            { value: "iMark", label: "i-Mark" },
            { value: "impulse", label: "Impulse" },
            { value: "mu", label: "MU" },
            { value: "npr", label: "NPR" },
            { value: "nqr", label: "NQR" },
            { value: "odeyssey", label: "Odeyssey" },
            { value: "pickup", label: "Pickup" },
            { value: "rodeo", label: "Rodeo" },
            { value: "stylus", label: "Stylus" },
            { value: "trooper", label: "Trooper" },
            { value: "vehicross", label: "VehiCROSS" },
        ],
        jaguar: [
            { value: "420", label: "420" },
            { value: "ePace", label: "E-Pace" },
            { value: "fpace", label: "F-Pace" },
            { value: "ftype", label: "F-Type" },
            { value: "sType", label: "S-Type" },
            { value: "xType", label: "X-Type" },
            { value: "xe", label: "XE" },
            { value: "xf", label: "XF" },
            { value: "xj", label: "XJ" },
            { value: "xj12", label: "XJ12" },
            { value: "xj6", label: "XJ6" },
            { value: "xj8", label: "XJ8" },
            { value: "xjr", label: "XJR" },
            { value: "xjs", label: "XJS" },
            { value: "xk", label: "XK" },
            { value: "xk8", label: "XK8" },
            { value: "xkr", label: "XKR" },
            { value: "xkss", label: "XKSS" },
        ],
        jeep: [
            { value: "cherokee", label: "Cherokee" },
            { value: "cj", label: "CJ" },
            { value: "comanche", label: "Comanche" },
            { value: "commander", label: "Commander" },
            { value: "compass", label: "Compass" },
            { value: "gladiator", label: "Gladiator" },
            { value: "grandCherokee", label: "Grand Cherokee" },
            { value: "grandWagoneer", label: "Grand Wagoneer" },
            { value: "liberty", label: "Liberty" },
            { value: "patriot", label: "Patriot" },
            { value: "renegade", label: "Renegade" },
            { value: "scrambler", label: "Scrambler" },
            { value: "wagoneer", label: "Wagoneer" },
            { value: "wrangler", label: "Wrangler" },
        ],
        kia: [
            { value: "amanti", label: "Amanti" },
            { value: "besta", label: "Besta" },
            { value: "borrego", label: "Borrego" },
            { value: "cadenza", label: "Cadenza" },
            { value: "carens", label: "Carens" },
            { value: "carnival", label: "Carnival" },
            { value: "ceed", label: "Ceed" },
            { value: "cerato", label: "Cerato" },
            { value: "clarus", label: "Clarus" },
            { value: "enterprise", label: "Enterprise" },
            { value: "forte", label: "Forte" },
            { value: "joice", label: "Joice" },
            { value: "k2700", label: "K2700" },
            { value: "k2900", label: "K2900" },
            { value: "k900", label: "K900" },
            { value: "magentis", label: "Magentis" },
            { value: "mentor", label: "Mentor" },
            { value: "mohave", label: "Mohave" },
            { value: "niro", label: "Niro" },
            { value: "olet", label: "Olet" },
            { value: "optima", label: "Optima" },
            { value: "optimaHybrid", label: "Optima Hybrid" },
            { value: "optimaPhev", label: "Optima PHEV" },
            { value: "picanto", label: "Picanto" },
            { value: "potentia", label: "Potentia" },
            { value: "pregio", label: "Pregio" },
            { value: "pride", label: "Pride" },
            { value: "proCeed", label: "ProCeed" },
            { value: "quoris", label: "Quoris" },
            { value: "retona", label: "Retona" },
            { value: "rio", label: "Rio" },
            { value: "roadster", label: "Roadster" },
            { value: "sedona", label: "Sedona" },
            { value: "sephia", label: "Sephia" },
            { value: "shuma", label: "Shuma" },
            { value: "sorento", label: "Sorento" },
            { value: "soul", label: "Soul" },
            { value: "spectra", label: "Spectra" },
            { value: "sportage", label: "Sportage" },
            { value: "stonic", label: "Stonic" },
            { value: "telluride", label: "Telluride" },
            { value: "venga", label: "Venga" },
        ],
        lamborghini: [
            { value: "aventador", label: "Aventador" },
            { value: "countach", label: "Countach" },
            { value: "diablo", label: "Diablo" },
            { value: "gallardo", label: "Gallardo" },
            { value: "huracan", label: "Huracan" },
            { value: "jalpa", label: "Jalpa" },
            { value: "lm", label: "LM" },
            { value: "murcielago", label: "Murcielago" },
            { value: "sestoElemento", label: "Sesto Elemento" },
            { value: "urus", label: "Urus" },
        ],
        lancia: [
            { value: "appla", label: "Appla" },
            { value: "beta", label: "Beta" },
            { value: "dedra", label: "Dedra" },
            { value: "flaminia", label: "Flaminia" },
            { value: "flavia", label: "Flavia" },
            { value: "fulvia", label: "Fulvia" },
            { value: "gamma", label: "Gamma" },
            { value: "kappa", label: "Kappa" },
            { value: "lybra", label: "Lybra" },
            { value: "montecarlo", label: "Montecarlo" },
            { value: "musa", label: "Musa" },
            { value: "phedra", label: "Phedra" },
            { value: "prisma", label: "Prisma" },
            { value: "stratos", label: "Stratos" },
            { value: "them", label: "Them" },
            { value: "thesis", label: "Thesis" },
            { value: "voyager", label: "Voyager" },
            { value: "y", label: "Y" },
            { value: "ypsilon", label: "Ypsilon" },
            { value: "zeta", label: "Zeta" },
        ],
        landRover: [
            { value: "defender", label: "Defender" },
            { value: "discovery", label: "Discovery" },
            { value: "discoverySport", label: "Discovery Sport" },
            { value: "freelander", label: "Freelander" },
            { value: "lr2", label: "LR2" },
            { value: "lr3", label: "LR3" },
            { value: "lr4", label: "LR4" },
            { value: "rangeRover", label: "Range Rover" },
            { value: "rangeRoverEvoque", label: "Range Rover Evoque" },
            { value: "rangeRoverSport", label: "Range Rover Sport" },
            { value: "rangeRoverVelar", label: "Range Rover Velar" },
        ],
        lexus: [
            { value: "ct", label: "CT" },
            { value: "es", label: "ES" },
            { value: "gs", label: "GS" },
            { value: "gx", label: "GX" },
            { value: "hs", label: "HS" },
            { value: "is", label: "IS" },
            { value: "lc", label: "LC" },
            { value: "lfa", label: "LFA" },
            { value: "ls", label: "LS" },
            { value: "lx", label: "LX" },
            { value: "nx", label: "NX" },
            { value: "rc", label: "RC" },
            { value: "rx", label: "RX" },
            { value: "sc", label: "SC" },
            { value: "ux", label: "UX" },
        ],
        lincoln: [
            { value: "aviator", label: "Aviator" },
            { value: "blackwood", label: "Blackwood" },
            { value: "continental", label: "Continental" },
            { value: "corsair", label: "Corsair" },
            { value: "ls", label: "LS" },
            { value: "marklt", label: "Mark LT" },
            { value: "markvi", label: "Mark VI" },
            { value: "markviii", label: "Mark VIII" },
            { value: "mkc", label: "MKC" },
            { value: "mks", label: "MKS" },
            { value: "mkt", label: "MKT" },
            { value: "mkx", label: "MKX" },
            { value: "mkz", label: "MKZ" },
            { value: "navigator", label: "Navigator" },
            { value: "townCar", label: "Town Car" },
            { value: "zephyr", label: "Zephyr" },
        ],
        lotus: [
            { value: "elise", label: "Elise" },
            { value: "elite", label: "Elite" },
            { value: "emerson", label: "Emerson" },
            { value: "esprit", label: "Esprit" },
            { value: "europe", label: "Europe" },
            { value: "evija", label: "Evija" },
            { value: "exige", label: "Exige" },
            { value: "seven", label: "Seven" },
            { value: "superSeven", label: "Super Seven" },
            { value: "twenty", label: "Twenty" },
        ],
        maserati: [
            { value: "3200gt", label: "3200 GT" },
            { value: "4200", label: "4200" },
            { value: "alfieri", label: "Alfieri" },
            { value: "biturbo", label: "Biturbo" },
            { value: "bora", label: "Bora" },
            { value: "ghibli", label: "Ghibli" },
            { value: "granCabrio", label: "GranCabrio" },
            { value: "granSport", label: "GranSport" },
            { value: "granTurismo", label: "GranTurismo" },
            { value: "indy", label: "Indy" },
            { value: "karif", label: "Karif" },
            { value: "kubang", label: "Kubang" },
            { value: "mc12", label: "MC12" },
            { value: "merak", label: "Merak" },
            { value: "quattroporte", label: "Quattroporte" },
            { value: "royale", label: "Royale" },
            { value: "spyder", label: "Spyder" },
        ],
        maybach: [
            { value: "57", label: "57" },
            { value: "62", label: "62" },
            { value: "maybach", label: "Maybach" },
        ],
        mazda: [
            { value: "121", label: "121" },
            { value: "2", label: "2" },
            { value: "3", label: "3" },
            { value: "323", label: "323" },
            { value: "5", label: "5" },
            { value: "6", label: "6" },
            { value: "616", label: "616" },
            { value: "626", label: "626" },
            { value: "818", label: "818" },
            { value: "929", label: "929" },
            { value: "bSeries", label: "B-Series" },
            { value: "cosmo", label: "Cosmo" },
            { value: "cx3", label: "CX-3" },
            { value: "cx30", label: "CX-30" },
            { value: "cx5", label: "CX-5" },
            { value: "cx7", label: "CX-7" },
            { value: "cx8", label: "CX-8" },
            { value: "cx9", label: "CX-9" },
            { value: "glc", label: "GLC" },
            { value: "laputa", label: "Laputa" },
            { value: "mPV", label: "MPV" },
            { value: "mX3", label: "MX-3" },
            { value: "mX30", label: "MX-30" },
            { value: "mX5", label: "MX-5" },
            { value: "mX6", label: "MX-6" },
            { value: "miata", label: "Miata" },
            { value: "millenia", label: "Millenia" },
            { value: "mpv", label: "MPV" },
            { value: "mx3", label: "MX-3" },
            { value: "mx5", label: "MX-5" },
            { value: "mx6", label: "MX-6" },
            { value: "premacy", label: "Premacy" },
            { value: "protege", label: "Protege" },
            { value: "r100", label: "R-100" },
            { value: "r130", label: "R-130" },
            { value: "r360Coupe", label: "R360 Coupe" },
            { value: "rX3", label: "RX-3" },
            { value: "rX4", label: "RX-4" },
            { value: "rX7", label: "RX-7" },
            { value: "rX8", label: "RX-8" },
            { value: "tribute", label: "Tribute" },
            { value: "verisa", label: "Verisa" },
            { value: "xedos6", label: "Xedos 6" },
            { value: "xedos9", label: "Xedos 9" },
        ],
        mclaren: [
            { value: "540c", label: "540C" },
            { value: "570gt", label: "570GT" },
            { value: "570s", label: "570S" },
            { value: "600lt", label: "600LT" },
            { value: "625c", label: "625C" },
            { value: "650s", label: "650S" },
            { value: "675lt", label: "675LT" },
            { value: "720s", label: "720S" },
            { value: "f1", label: "F1" },
            { value: "gt", label: "GT" },
            { value: "m6gt", label: "M6GT" },
            { value: "mp412c", label: "MP4-12C" },
            { value: "p1", label: "P1" },
            { value: "senna", label: "Senna" },
        ],
        mercedesBenz: [
            { value: "aClass", label: "A-Class" },
            { value: "amgGt", label: "AMG GT" },
            { value: "bClass", label: "B-Class" },
            { value: "cClass", label: "C-Class" },
            { value: "cLassCls", label: "CLass CLS" },
            { value: "cLassClsShootingBrake", label: "CLass CLS Shooting Brake" },
            { value: "cLassEqc", label: "CLass EQC" },
            { value: "cLassGlcCoupe", label: "CLass GLC Coupe" },
            { value: "cLassGleCoupe", label: "CLass GLE Coupe" },
            { value: "cLassGls", label: "CLass GLS" },
            { value: "eClass", label: "E-Class" },
            { value: "gClass", label: "G-Class" },
            { value: "gLa", label: "GLA" },
            { value: "gLaClass", label: "GLA-Class" },
            { value: "gLe", label: "GLE" },
            { value: "gLeClass", label: "GLE-Class" },
            { value: "gLf", label: "GLF" },
            { value: "gLkClass", label: "GLK-Class" },
            { value: "gLs", label: "GLS" },
            { value: "gLsClass", label: "GLS-Class" },
            { value: "mClass", label: "M-Class" },
            { value: "maybachSClass", label: "Maybach S-Class" },
            { value: "mLClass", label: "ML-Class" },
            { value: "metris", label: "Metris" },
            { value: "rClass", label: "R-Class" },
            { value: "sClass", label: "S-Class" },
            { value: "sLClass", label: "SL-Class" },
            { value: "sLc", label: "SLC" },
            { value: "sLkClass", label: "SLK-Class" },
            { value: "sLsAmgClass", label: "SLS AMG-Class" },
            { value: "sLsClass", label: "SLS-Class" },
            { value: "sprinter", label: "Sprinter" },
            { value: "viano", label: "Viano" },
            { value: "vito", label: "Vito" },
        ],
        mercury: [
            { value: "capri", label: "Capri" },
            { value: "comet", label: "Comet" },
            { value: "cougar", label: "Cougar" },
            { value: "grandMarquis", label: "Grand Marquis" },
            { value: "lynx", label: "Lynx" },
            { value: "marauder", label: "Marauder" },
            { value: "mariner", label: "Mariner" },
            { value: "marquis", label: "Marquis" },
            { value: "milan", label: "Milan" },
            { value: "montclair", label: "Montclair" },
            { value: "monterey", label: "Monterey" },
            { value: "mountaineer", label: "Mountaineer" },
            { value: "mystique", label: "Mystique" },
            { value: "parkLane", label: "Park Lane" },
            { value: "sable", label: "Sable" },
            { value: "topaz", label: "Topaz" },
            { value: "tracer", label: "Tracer" },
            { value: "villager", label: "Villager" },
        ],
        mini: [
            { value: "clubman", label: "Clubman" },
            { value: "cooper", label: "Cooper" },
            { value: "cooperCountryman", label: "Cooper Countryman" },
            { value: "cooperCoupe", label: "Cooper Coupe" },
            { value: "cooperPaceman", label: "Cooper Paceman" },
            { value: "cooperRoadster", label: "Cooper Roadster" },
            { value: "cooperS", label: "Cooper S" },
            { value: "cooperSCountryman", label: "Cooper S Countryman" },
            { value: "cooperSCoupe", label: "Cooper S Coupe" },
            { value: "cooperSPaceman", label: "Cooper S Paceman" },
            { value: "cooperSRoadster", label: "Cooper S Roadster" },
            { value: "countryman", label: "Countryman" },
            { value: "coupe", label: "Coupe" },
            { value: "paceman", label: "Paceman" },
            { value: "roadster", label: "Roadster" },
        ],
        mitsubishi: [
            { value: "3000gt", label: "3000GT" },
            { value: "asx", label: "ASX" },
            { value: "carisma", label: "Carisma" },
            { value: "colt", label: "Colt" },
            { value: "cordia", label: "Cordia" },
            { value: "delica", label: "Delica" },
            { value: "diamante", label: "Diamante" },
            { value: "eclipse", label: "Eclipse" },
            { value: "endeavor", label: "Endeavor" },
            { value: "expo", label: "Expo" },
            { value: "galant", label: "Galant" },
            { value: "grandis", label: "Grandis" },
            { value: "iMiev", label: "i-Miev" },
            { value: "l200", label: "L200" },
            { value: "l300", label: "L300" },
            { value: "lancer", label: "Lancer" },
            { value: "montero", label: "Montero" },
            { value: "outlander", label: "Outlander" },
            { value: "pajero", label: "Pajero" },
            { value: "pajeroPinin", label: "Pajero Pinin" },
            { value: "pajeroSport", label: "Pajero Sport" },
            { value: "precis", label: "Precis" },
            { value: "raider", label: "Raider" },
            { value: "rVR", label: "RVR" },
            { value: "shogun", label: "Shogun" },
            { value: "shogunPinin", label: "Shogun Pinin" },
            { value: "sigma", label: "Sigma" },
            { value: "spaceGear", label: "Space Gear" },
            { value: "spaceRunner", label: "Space Runner" },
            { value: "spaceStar", label: "Space Star" },
            { value: "spaceWagon", label: "Space Wagon" },
            { value: "starion", label: "Starion" },
            { value: "tredia", label: "Tredia" },
            { value: "triton", label: "Triton" },
        ],
        nissan: [
            { value: "100nx", label: "100NX" },
            { value: "200sx", label: "200SX" },
            { value: "240sx", label: "240SX" },
            { value: "280zx", label: "280ZX" },
            { value: "300zx", label: "300ZX" },
            { value: "350z", label: "350Z" },
            { value: "370z", label: "370Z" },
            { value: "almera", label: "Almera" },
            { value: "almeraTino", label: "Almera Tino" },
            { value: "altima", label: "Altima" },
            { value: "armada", label: "Armada" },
            { value: "bluebird", label: "Bluebird" },
            { value: "cedric", label: "Cedric" },
            { value: "cima", label: "Cima" },
            { value: "cube", label: "Cube" },
            { value: "evalia", label: "Evalia" },
            { value: "fairladyZ", label: "Fairlady Z" },
            { value: "frontier", label: "Frontier" },
            { value: "gtR", label: "GT-R" },
            { value: "interstar", label: "Interstar" },
            { value: "juke", label: "Juke" },
            { value: "kicks", label: "Kicks" },
            { value: "kingCab", label: "King Cab" },
            { value: "kubistar", label: "Kubistar" },
            { value: "largo", label: "Largo" },
            { value: "laurel", label: "Laurel" },
            { value: "leaf", label: "Leaf" },
            { value: "maxima", label: "Maxima" },
            { value: "micra", label: "Micra" },
            { value: "murano", label: "Murano" },
            { value: "navara", label: "Navara" },
            { value: "note", label: "Note" },
            { value: "np300", label: "NP300" },
            { value: "nv200", label: "NV200" },
            { value: "nv400", label: "NV400" },
            { value: "pathfinder", label: "Pathfinder" },
            { value: "patrol", label: "Patrol" },
            { value: "pickUp", label: "Pick Up" },
            { value: "pixo", label: "Pixo" },
            { value: "prairie", label: "Prairie" },
            { value: "primastar", label: "Primastar" },
            { value: "primera", label: "Primera" },
            { value: "pulsar", label: "Pulsar" },
            { value: "quest", label: "Quest" },
            { value: "rogue", label: "Rogue" },
            { value: "rogueSelect", label: "Rogue Select" },
            { value: "sentra", label: "Sentra" },
            { value: "silvia", label: "Silvia" },
            { value: "skyline", label: "Skyline" },
            { value: "stanza", label: "Stanza" },
            { value: "sunny", label: "Sunny" },
            { value: "teana", label: "Teana" },
            { value: "terrano", label: "Terrano" },
            { value: "tiida", label: "Tiida" },
            { value: "titan", label: "Titan" },
            { value: "trade", label: "Trade" },
            { value: "ud", label: "UD" },
            { value: "urvan", label: "Urvan" },
            { value: "vanette", label: "Vanette" },
            { value: "versa", label: "Versa" },
            { value: "xterra", label: "Xterra" },
            { value: "z", label: "Z" },
        ],
        noble: [
            { value: "m10", label: "M10" },
            { value: "m12", label: "M12" },
            { value: "m400", label: "M400" },
            { value: "m600", label: "M600" },
        ],
        opel: [
            { value: "adam", label: "Adam" },
            { value: "admiral", label: "Admiral" },
            { value: "agila", label: "Agila" },
            { value: "ampera", label: "Ampera" },
            { value: "antara", label: "Antara" },
            { value: "arena", label: "Arena" },
            { value: "ascona", label: "Ascona" },
            { value: "astra", label: "Astra" },
            { value: "calibra", label: "Calibra" },
            { value: "campo", label: "Campo" },
            { value: "cascada", label: "Cascada" },
            { value: "combo", label: "Combo" },
            { value: "commodore", label: "Commodore" },
            { value: "corsa", label: "Corsa" },
            { value: "crosslandX", label: "Crossland X" },
            { value: "frontera", label: "Frontera" },
            { value: "gT", label: "GT" },
            { value: "insignia", label: "Insignia" },
            { value: "kadett", label: "Kadett" },
            { value: "kappa", label: "Kappa" },
            { value: "manta", label: "Manta" },
            { value: "meriva", label: "Meriva" },
            { value: "mokka", label: "Mokka" },
            { value: "monterey", label: "Monterey" },
            { value: "monza", label: "Monza" },
            { value: "movano", label: "Movano" },
            { value: "neMovano", label: "NeMovano" },
            { value: "omega", label: "Omega" },
            { value: "rakE", label: "RakE" },
            { value: "reKord", label: "ReKord" },
            { value: "senator", label: "Senator" },
            { value: "signum", label: "Signum" },
            { value: "sintra", label: "Sintra" },
            { value: "speedster", label: "Speedster" },
            { value: "tigra", label: "Tigra" },
            { value: "tour", label: "Tour" },
            { value: "vectra", label: "Vectra" },
            { value: "vita", label: "Vita" },
            { value: "vivaro", label: "Vivaro" },
            { value: "zafira", label: "Zafira" },
        ],
        pagani: [
            { value: "huayra", label: "Huayra" },
            { value: "huayraRoadster", label: "Huayra Roadster" },
            { value: "zonda", label: "Zonda" },
            { value: "zondaCinque", label: "Zonda Cinque" },
            { value: "zondaF", label: "Zonda F" },
            { value: "zondaRoadster", label: "Zonda Roadster" },
        ],
        peugeot: [
            { value: "1007", label: "1007" },
            { value: "104", label: "104" },
            { value: "106", label: "106" },
            { value: "107", label: "107" },
            { value: "108", label: "108" },
            { value: "2008", label: "2008" },
            { value: "204", label: "204" },
            { value: "205", label: "205" },
            { value: "206", label: "206" },
            { value: "207", label: "207" },
            { value: "208", label: "208" },
            { value: "3008", label: "3008" },
            { value: "301", label: "301" },
            { value: "304", label: "304" },
            { value: "305", label: "305" },
            { value: "306", label: "306" },
            { value: "307", label: "307" },
            { value: "308", label: "308" },
            { value: "309", label: "309" },
            { value: "4007", label: "4007" },
            { value: "4008", label: "4008" },
            { value: "403", label: "403" },
            { value: "404", label: "404" },
            { value: "405", label: "405" },
            { value: "406", label: "406" },
            { value: "407", label: "407" },
            { value: "408", label: "408" },
            { value: "5008", label: "5008" },
            { value: "504", label: "504" },
            { value: "505", label: "505" },
            { value: "508", label: "508" },
            { value: "604", label: "604" },
            { value: "605", label: "605" },
            { value: "607", label: "607" },
            { value: "608", label: "608" },
            { value: "806", label: "806" },
            { value: "807", label: "807" },
            { value: "Bipper", label: "Bipper" },
            { value: "expert", label: "Expert" },
            { value: "ion", label: "ION" },
            { value: "ionCUTe", label: "ION CUTE" },
            { value: "partner", label: "Partner" },
            { value: "rcz", label: "RCZ" },
            { value: "rifter", label: "Rifter" },
            { value: "traveller", label: "Traveller" },
        ],
        plymouth: [
            { value: "acclaim", label: "Acclaim" },
            { value: "barracuda", label: "Barracuda" },
            { value: "belvedere", label: "Belvedere" },
            { value: "breeze", label: "Breeze" },
            { value: "caravelle", label: "Caravelle" },
            { value: "champ", label: "Champ" },
            { value: "cranbrook", label: "Cranbrook" },
            { value: "duster", label: "Duster" },
            { value: "fury", label: "Fury" },
            { value: "gtx", label: "GTX" },
            { value: "horizon", label: "Horizon" },
            { value: "laser", label: "Laser" },
            { value: "neon", label: "Neon" },
            { value: "prowler", label: "Prowler" },
            { value: "reliant", label: "Reliant" },
            { value: "sapporo", label: "Sapporo" },
            { value: "sundance", label: "Sundance" },
            { value: "valiant", label: "Valiant" },
            { value: "volare", label: "Volare" },
            { value: "voyager", label: "Voyager" },
        ],
        pontiac: [
            { value: "1000", label: "1000" },
            { value: "2000Sunbird", label: "2000 Sunbird" },
            { value: "6000", label: "6000" },
            { value: "aztek", label: "Aztek" },
            { value: "banshee", label: "Banshee" },
            { value: "bonneville", label: "Bonneville" },
            { value: "catalina", label: "Catalina" },
            { value: "fiero", label: "Fiero" },
            { value: "firebird", label: "Firebird" },
            { value: "g3", label: "G3" },
            { value: "g4", label: "G4" },
            { value: "g5", label: "G5" },
            { value: "g6", label: "G6" },
            { value: "g8", label: "G8" },
            { value: "grandAm", label: "Grand Am" },
            { value: "grandPrix", label: "Grand Prix" },
            { value: "gto", label: "GTO" },
            { value: "lemans", label: "LeMans" },
            { value: "montana", label: "Montana" },
            { value: "solstice", label: "Solstice" },
            { value: "sunbird", label: "Sunbird" },
            { value: "sunfire", label: "Sunfire" },
            { value: "torrent", label: "Torrent" },
            { value: "trans", label: "Trans" },
            { value: "vibe", label: "Vibe" },
        ],
        porsche: [
            { value: "356", label: "356" },
            { value: "718", label: "718" },
            { value: "718Boxster", label: "718 Boxster" },
            { value: "718Cayman", label: "718 Cayman" },
            { value: "804", label: "804" },
            { value: "550", label: "550" },
            { value: "911", label: "911" },
            { value: "911Gt1", label: "911 GT1" },
            { value: "911Gt2", label: "911 GT2" },
            { value: "911Gt3", label: "911 GT3" },
            { value: "911Gt3Rs", label: "911 GT3 RS" },
            { value: "911R", label: "911 R" },
            { value: "911Targa", label: "911 Targa" },
            { value: "914", label: "914" },
            { value: "918", label: "918" },
            { value: "924", label: "924" },
            { value: "928", label: "928" },
            { value: "944", label: "944" },
            { value: "959", label: "959" },
            { value: "968", label: "968" },
            { value: "boxster", label: "Boxster" },
            { value: "carrerGt", label: "Carrer GT" },
            { value: "carreraGt", label: "Carrera GT" },
            { value: "cayenne", label: "Cayenne" },
            { value: "cayman", label: "Cayman" },
            { value: "macan", label: "Macan" },
            { value: "panamera", label: "Panamera" },
        ],
        proton: [
            { value: "400", label: "400" },
            { value: "ATlIs", label: "ATlIs" },
            { value: "persona", label: "Persona" },
            { value: "saga", label: "Saga" },
            { value: "satria", label: "Satria" },
            { value: "waja", label: "Waja" },
        ],
        ram: [
            { value: "1500", label: "1500" },
            { value: "2500", label: "2500" },
            { value: "3500", label: "3500" },
            { value: "charger", label: "Charger" },
            { value: "dakota", label: "Dakota" },
            { value: "d150", label: "D150" },
            { value: "d250", label: "D250" },
            { value: "d350", label: "D350" },
            { value: "dart", label: "Dart" },
            { value: "daytona", label: "Daytona" },
            { value: "durango", label: "Durango" },
            { value: "journey", label: "Journey" },
            { value: "magnum", label: "Magnum" },
            { value: "neon", label: "Neon" },
            { value: "nitro", label: "Nitro" },
            { value: "ram", label: "Ram" },
            { value: "ramVan", label: "Ram Van" },
            { value: "stealth", label: "Stealth" },
            { value: "stratus", label: "Stratus" },
            { value: "viper", label: "Viper" },
        ],
        renault: [
            { value: "11", label: "11" },
            { value: "12", label: "12" },
            { value: "14", label: "14" },
            { value: "15", label: "15" },
            { value: "16", label: "16" },
            { value: "17", label: "17" },
            { value: "18", label: "18" },
            { value: "19", label: "19" },
            { value: "20", label: "20" },
            { value: "21", label: "21" },
            { value: "25", label: "25" },
            { value: "30", label: "30" },
            { value: "4", label: "4" },
            { value: "5", label: "5" },
            { value: "6", label: "6" },
            { value: "9", label: "9" },
            { value: "alaskan", label: "Alaskan" },
            { value: "avantime", label: "Avantime" },
            { value: "captur", label: "Captur" },
            { value: "clio", label: "Clio" },
            { value: "dauphine", label: "Dauphine" },
            { value: "espace", label: "Espace" },
            { value: "floride", label: "Floride" },
            { value: "fluence", label: "Fluence" },
            { value: "fregate", label: "Fregate" },
            { value: "kangoo", label: "Kangoo" },
            { value: "koleos", label: "Koleos" },
            { value: "laguna", label: "Laguna" },
            { value: "latitude", label: "Latitude" },
            { value: "logan", label: "Logan" },
            { value: "master", label: "Master" },
            { value: "maxity", label: "Maxity" },
            { value: "megane", label: "Megane" },
            { value: "modus", label: "Modus" },
            { value: "nevada", label: "Nevada" },
            { value: "pulse", label: "Pulse" },
            { value: "rEspace", label: "REspace" },
            { value: "rodeo", label: "Rodeo" },
            { value: "safrane", label: "Safrane" },
            { value: "sandero", label: "Sandero" },
            { value: "scala", label: "Scala" },
            { value: "scenic", label: "Scenic" },
            { value: "sportSpider", label: "Sport Spider" },
            { value: "symbol", label: "Symbol" },
            { value: "talento", label: "Talento" },
            { value: "thalia", label: "Thalia" },
            { value: "trafic", label: "Trafic" },
            { value: "twingo", label: "Twingo" },
            { value: "velsatis", label: "Velsatis" },
            { value: "wind", label: "Wind" },
            { value: "zoe", label: "Zoe" },
        ],
        rollsRoyce: [
            { value: "camargue", label: "Camargue" },
            { value: "corniche", label: "Corniche" },
            { value: "cullinan", label: "Cullinan" },
            { value: "dawn", label: "Dawn" },
            { value: "ghost", label: "Ghost" },
            { value: "parkward", label: "Parkward" },
            { value: "phantom", label: "Phantom" },
            { value: "silverCloud", label: "Silver Cloud" },
            { value: "silverDawn", label: "Silver Dawn" },
            { value: "silverSeraph", label: "Silver Seraph" },
            { value: "silverShadow", label: "Silver Shadow" },
            { value: "silverSpirit", label: "Silver Spirit" },
            { value: "silverSpur", label: "Silver Spur" },
            { value: "wraith", label: "Wraith" },
        ],
        saab: [
            { value: "9_3", label: "9-3" },
            { value: "9_3X", label: "9-3X" },
            { value: "9_4X", label: "9-4X" },
            { value: "9_5", label: "9-5" },
            { value: "9_7X", label: "9-7X" },
            { value: "900", label: "900" },
            { value: "9000", label: "9000" },
        ],
        saleen: [
            { value: "S7", label: "S7" },
        ],
        saturn: [
            { value: "astra", label: "Astra" },
            { value: "aura", label: "Aura" },
            { value: "ion", label: "ION" },
            { value: "l_series", label: "L-Series" },
            { value: "outlook", label: "Outlook" },
            { value: "relay", label: "Relay" },
            { value: "sky", label: "Sky" },
            { value: "vue", label: "Vue" },
        ],
        scion: [
            { value: "fr_s", label: "FR-S" },
            { value: "ia", label: "iA" },
            { value: "im", label: "iM" },
            { value: "iq", label: "iQ" },
            { value: "tc", label: "tC" },
            { value: "xa", label: "xA" },
            { value: "xb", label: "xB" },
            { value: "xd", label: "xD" },
        ],
        seat: [
            { value: "124", label: "124" },
            { value: "127", label: "127" },
            { value: "128", label: "128" },
            { value: "131", label: "131" },
            { value: "132", label: "132" },
            { value: "133", label: "133" },
            { value: "600", label: "600" },
            { value: "850", label: "850" },
            { value: "alhambra", label: "Alhambra" },
            { value: "altea", label: "Altea" },
            { value: "arona", label: "Arona" },
            { value: "ateca", label: "Ateca" },
            { value: "cordoba", label: "Cordoba" },
            { value: "exeo", label: "Exeo" },
            { value: "fura", label: "Fura" },
            { value: "ibiza", label: "Ibiza" },
            { value: "ledo", label: "Ledo" },
            { value: "marbella", label: "Marbella" },
            { value: "mii", label: "Mii" },
            { value: "ronda", label: "Ronda" },
            { value: "tarraco", label: "Tarraco" },
            { value: "toledo", label: "Toledo" },
        ],
        skoda: [
            { value: "100", label: "100" },
            { value: "105", label: "105" },
            { value: "120", label: "120" },
            { value: "130", label: "130" },
            { value: "135", label: "135" },
            { value: "136", label: "136" },
            { value: "Citigo", label: "Citigo" },
            { value: "fabia", label: "Fabia" },
            { value: "favorit", label: "Favorit" },
            { value: "felicia", label: "Felicia" },
            { value: "forman", label: "Forman" },
            { value: "kamiq", label: "Kamiq" },
            { value: "karoq", label: "Karoq" },
            { value: "kodiaq", label: "Kodiaq" },
            { value: "octavia", label: "Octavia" },
            { value: "rapID", label: "Rapid" },
            { value: "roomster", label: "Roomster" },
            { value: "superb", label: "Superb" },
            { value: "yeti", label: "Yeti" },
        ],
        smart: [
            { value: "forFour", label: "ForFour" },
            { value: "forTwo", label: "ForTwo" },
            { value: "roadster", label: "Roadster" },
        ],
        ssangyong: [
            { value: "actyon", label: "Actyon" },
            { value: "actyonSports", label: "Actyon Sports" },
            { value: "chairman", label: "Chairman" },
            { value: "korando", label: "Korando" },
            { value: "kyron", label: "Kyron" },
            { value: "musso", label: "Musso" },
            { value: "rexton", label: "Rexton" },
            { value: "rodIus", label: "Rodius" },
            { value: "tivoli", label: "Tivoli" },
            { value: "XLV", label: "XLV" },
        ],
        subaru: [
            { value: "Baja", label: "Baja" },
            { value: "brat", label: "Brat" },
            { value: "brz", label: "BRZ" },
            { value: "forester", label: "Forester" },
            { value: "Impreza", label: "Impreza" },
            { value: "ImprezaWRX", label: "Impreza WRX" },
            { value: "Justy", label: "Justy" },
            { value: "Legacy", label: "Legacy" },
            { value: "loyale", label: "Loyale" },
            { value: "outback", label: "Outback" },
            { value: "svx", label: "SVX" },
            { value: "tribeca", label: "Tribeca" },
            { value: "vivio", label: "Vivio" },
            { value: "WRX", label: "WRX" },
            { value: "XT", label: "XT" },
            { value: "XV_Crosstrek", label: "XV Crosstrek" },
        ],
        suzuki: [
            { value: "Aerio", label: "Aerio" },
            { value: "Alto", label: "Alto" },
            { value: "APV", label: "APV" },
            { value: "Cappuccino", label: "Cappuccino" },
            { value: "Carry", label: "Carry" },
            { value: "Celerio", label: "Celerio" },
            { value: "Cervo", label: "Cervo" },
            { value: "Esteem", label: "Esteem" },
            { value: "Every", label: "Every" },
            { value: "forenza", label: "Forenza" },
            { value: "Forsa", label: "Forsa" },
            { value: "grAnd_VitAra", label: "Grand Vitara" },
            { value: "Ignis", label: "Ignis" },
            { value: "Jimny", label: "Jimny" },
            { value: "Kizashi", label: "Kizashi" },
            { value: "Liana", label: "Liana" },
            { value: "lj", label: "LJ" },
            { value: "Samurai", label: "Samurai" },
            { value: "Sidekick", label: "Sidekick" },
            { value: "Splash", label: "Splash" },
            { value: "super_Carry", label: "Super Carry" },
            { value: "Swift", label: "Swift" },
            { value: "SX4", label: "SX4" },
            { value: "Verona", label: "Verona" },
            { value: "Vitara", label: "Vitara" },
            { value: "Wagon_R", label: "Wagon R" },
            { value: "X_90", label: "X-90" },
        ],
        talbot: [
            { value: "1100", label: "1100" },
            { value: "1307", label: "1307" },
            { value: "1308", label: "1308" },
            { value: "1510", label: "1510" },
            { value: "alpine", label: "Alpine" },
            { value: "horizon", label: "Horizon" },
            { value: "samba", label: "Samba" },
            { value: "solara", label: "Solara" },
            { value: "tagora", label: "Tagora" },
        ],
        tata: [
            { value: "aria", label: "Aria" },
            { value: "estate", label: "Estate" },
            { value: "indica", label: "Indica" },
            { value: "indigo", label: "Indigo" },
            { value: "nano", label: "Nano" },
            { value: "safari", label: "Safari" },
            { value: "sierra", label: "Sierra" },
            { value: "telco", label: "Telco" },
            { value: "tElcoline", label: "Telcoline" },
            { value: "victa", label: "Victa" },
            { value: "xenon", label: "Xenon" },
            { value: "xover", label: "XOver" },
        ],
        tatra: [
            { value: "57", label: "57" },
            { value: "77", label: "77" },
            { value: "87", label: "87" },
            { value: "97", label: "97" },
            { value: "600", label: "600" },
            { value: "603", label: "603" },
            { value: "700", label: "700" },
        ],
        tesla: [
            { value: "roadster", label: "Roadster" },
            { value: "model_S", label: "Model S" },
            { value: "model_3", label: "Model 3" },
            { value: "model_X", label: "Model X" },
            { value: "model_Y", label: "Model Y" },
            { value: "cybertruck", label: "Cybertruck" },
        ],
        toyota: [
            { value: "4runner", label: "4Runner" },
            { value: "86", label: "86" },
            { value: "aurion", label: "Aurion" },
            { value: "avalon", label: "Avalon" },
            { value: "avensis", label: "Avensis" },
            { value: "aygo", label: "Aygo" },
            { value: "c_hr", label: "C-HR" },
            { value: "camry", label: "Camry" },
            { value: "celica", label: "Celica" },
            { value: "corolla", label: "Corolla" },
            { value: "corolla_Cross", label: "Corolla Cross" },
            { value: "corona", label: "Corona" },
            { value: "cressida", label: "Cressida" },
            { value: "crown", label: "Crown" },
            { value: "echo", label: "Echo" },
            { value: "fj_Cruiser", label: "FJ Cruiser" },
            { value: "fortuner", label: "Fortuner" },
            { value: "GR_86", label: "GR 86" },
            { value: "GT86", label: "GT86" },
            { value: "hiace", label: "Hiace" },
            { value: "highlander", label: "Highlander" },
            { value: "hilux", label: "Hilux" },
            { value: "iq", label: "iQ" },
            { value: "kluger", label: "Kluger" },
            { value: "land_Cruiser", label: "Land Cruiser" },
            { value: "matrix", label: "Matrix" },
            { value: "mr_2", label: "MR2" },
            { value: "paseo", label: "Paseo" },
            { value: "pickup", label: "Pickup" },
            { value: "previa", label: "Previa" },
            { value: "prius", label: "Prius" },
            { value: "prius_C", label: "Prius C" },
            { value: "prius_Plug_in", label: "Prius Plug-in" },
            { value: "prius_Prime", label: "Prius Prime" },
            { value: "prius_V", label: "Prius V" },
            { value: "ractis", label: "Ractis" },
            { value: "rav4", label: "RAV4" },
            { value: "sequoia", label: "Sequoia" },
            { value: "sienna", label: "Sienna" },
            { value: "solara", label: "Solara" },
            { value: "starlet", label: "Starlet" },
            { value: "supra", label: "Supra" },
            { value: "t100", label: "T100" },
            { value: "tacoma", label: "Tacoma" },
            { value: "tundra", label: "Tundra" },
            { value: "venza", label: "Venza" },
            { value: "verso", label: "Verso" },
            { value: "will", label: "Will" },
            { value: "yaris", label: "Yaris" },
        ],
        trabant: [
            { value: "500", label: "500" },
            { value: "600", label: "600" },
            { value: "601", label: "601" },
            { value: "kombi", label: "Kombi" },
            { value: "p50", label: "P50" },
            { value: "p60", label: "P60" },
        ],
        triumph: [
            { value: "acclaim", label: "Acclaim" },
            { value: "Dolomite", label: "Dolomite" },
            { value: "GT6", label: "GT6" },
            { value: "herald", label: "Herald" },
            { value: "spitfire", label: "Spitfire" },
            { value: "stag", label: "Stag" },
            { value: "tr2", label: "TR2" },
            { value: "tr3", label: "TR3" },
            { value: "tr3a", label: "TR3A" },
            { value: "tr4", label: "TR4" },
            { value: "tr4a", label: "TR4A" },
            { value: "tr5", label: "TR5" },
            { value: "tr6", label: "TR6" },
            { value: "tr7", label: "TR7" },
            { value: "tr8", label: "TR8" },
            { value: "vitesse", label: "Vitesse" },
        ],
        tvr: [
            { value: "280i", label: "280i" },
            { value: "350i", label: "350i" },
            { value: "390SE", label: "390SE" },
            { value: "400SE", label: "400SE" },
            { value: "420SE", label: "420SE" },
            { value: "450SE", label: "450SE" },
            { value: "Cerbera", label: "Cerbera" },
            { value: "chimaera", label: "Chimaera" },
            { value: "griffith", label: "Griffith" },
            { value: "s", label: "S" },
            { value: "s2", label: "S2" },
            { value: "s3", label: "S3" },
            { value: "s4", label: "S4" },
            { value: "sagaris", label: "Sagaris" },
            { value: "t350", label: "T350" },
            { value: "tamora", label: "Tamora" },
            { value: "tasmin", label: "Tasmin" },
            { value: "tuscan", label: "Tuscan" },
        ],

        vauxhall: [
            { value: "adAm", label: "Adam" },
            { value: "agila", label: "Agila" },
            { value: "Ampera", label: "Ampera" },
            { value: "antara", label: "Antara" },
            { value: "astra", label: "Astra" },
            { value: "astravan", label: "Astravan" },
            { value: "calibra", label: "Calibra" },
            { value: "cascada", label: "Cascada" },
            { value: "cavalier", label: "Cavalier" },
            { value: "combo", label: "Combo" },
            { value: "commodore", label: "Commodore" },
            { value: "corsa", label: "Corsa" },
            { value: "crossland_X", label: "Crossland X" },
            { value: "frontera", label: "Frontera" },
            { value: "grandlAnd_X", label: "Grandland X" },
            { value: "Insignia", label: "Insignia" },
            { value: "meriva", label: "Meriva" },
            { value: "mokka", label: "Mokka" },
            { value: "monterey", label: "Monterey" },
            { value: "monza", label: "Monza" },
            { value: "movano", label: "Movano" },
            { value: "nova", label: "Nova" },
            { value: "omega", label: "Omega" },
            { value: "rascal", label: "Rascal" },
            { value: "senator", label: "Senator" },
            { value: "signum", label: "Signum" },
            { value: "sintra", label: "Sintra" },
            { value: "tigra", label: "Tigra" },
            { value: "vivAro", label: "Vivaro" },
            { value: "vivAro_tour", label: "Vivaro Tour" },
            { value: "VXR8", label: "VXR8" },
            { value: "wyvern", label: "Wyvern" },
            { value: "zafira", label: "Zafira" },
        ],
        vector: [
            { value: "avtechWX3", label: "Avtech WX3" },
            { value: "avtechWX3R", label: "Avtech WX3R" },
            { value: "avtechWX8", label: "Avtech WX8" },
            { value: "M12", label: "M12" },
            { value: "wx3", label: "WX3" },
            { value: "wx3R", label: "WX3R" },
            { value: "wx8", label: "WX8" },
        ],
        venturi: [
            { value: "200", label: "200" },
            { value: "210", label: "210" },
            { value: "260", label: "260" },
            { value: "300", label: "300" },
            { value: "400", label: "400" },
            { value: "Atlantique", label: "Atlantique" },
            { value: "fetish", label: "Fetish" },
            { value: "grand_tourisme", label: "Grand Tourisme" },
        ],
        volkswagen: [
            { value: "amarok", label: "Amarok" },
            { value: "arteon", label: "Arteon" },
            { value: "beetle", label: "Beetle" },
            { value: "bora", label: "Bora" },
            { value: "caddy", label: "Caddy" },
            { value: "cc", label: "CC" },
            { value: "corrado", label: "Corrado" },
            { value: "crafter", label: "Crafter" },
            { value: "eos", label: "Eos" },
            { value: "fox", label: "Fox" },
            { value: "golf", label: "Golf" },
            { value: "golf_Alltrack", label: "Golf Alltrack" },
            { value: "golf_Cabrio", label: "Golf Cabrio" },
            { value: "golf_Plus", label: "Golf Plus" },
            { value: "golf_R", label: "Golf R" },
            { value: "golf_Sportsvan", label: "Golf Sportsvan" },
            { value: "golf_GT", label: "Golf GT" },
            { value: "golf_GTD", label: "Golf GTD" },
            { value: "golf_GTE", label: "Golf GTE" },
            { value: "golf_GTI", label: "Golf GTI" },
            { value: "golf_R32", label: "Golf R32" },
            { value: "golf_Variant", label: "Golf Variant" },
            { value: "golf_Variant_GT", label: "Golf Variant GT" },
            { value: "jetta", label: "Jetta" },
            { value: "kaefer", label: "Kaefer" },
            { value: "karmann_Ghia", label: "Karmann Ghia" },
            { value: "lupo", label: "Lupo" },
            { value: "multivan", label: "Multivan" },
            { value: "parati", label: "Parati" },
            { value: "passat", label: "Passat" },
            { value: "passat_Alltrack", label: "Passat Alltrack" },
            { value: "passat_CC", label: "Passat CC" },
            { value: "passat_CL", label: "Passat CL" },
            { value: "passat_Estate", label: "Passat Estate" },
            { value: "passat_GTE", label: "Passat GTE" },
            { value: "phaeton", label: "Phaeton" },
            { value: "pointer", label: "Pointer" },
            { value: "polo", label: "Polo" },
            { value: "routan", label: "Routan" },
            { value: "saveiro", label: "Saveiro" },
            { value: "scirocco", label: "Scirocco" },
            { value: "sharan", label: "Sharan" },
            { value: "t_cross", label: "T-Cross" },
            { value: "taos", label: "Taos" },
            { value: "tarek", label: "Tarek" },
            { value: "tiguan", label: "Tiguan" },
            { value: "tiguan_Allspace", label: "Tiguan Allspace" },
            { value: "touareg", label: "Touareg" },
            { value: "touran", label: "Touran" },
            { value: "up", label: "Up" },
            { value: "vento", label: "Vento" },
        ],
        volvo: [
            { value: "240", label: "240" },
            { value: "260", label: "260" },
            { value: "340", label: "340" },
            { value: "360", label: "360" },
            { value: "440", label: "440" },
            { value: "460", label: "460" },
            { value: "480", label: "480" },
            { value: "66", label: "66" },
            { value: "740", label: "740" },
            { value: "760", label: "760" },
            { value: "780", label: "780" },
            { value: "850", label: "850" },
            { value: "940", label: "940" },
            { value: "960", label: "960" },
            { value: "c30", label: "C30" },
            { value: "c70", label: "C70" },
            { value: "duett", label: "Duett" },
            { value: "s40", label: "S40" },
            { value: "s60", label: "S60" },
            { value: "s70", label: "S70" },
            { value: "s80", label: "S80" },
            { value: "s90", label: "S90" },
            { value: "v40", label: "V40" },
            { value: "v40_Cross_Country", label: "V40 Cross Country" },
            { value: "v50", label: "V50" },
            { value: "v60", label: "V60" },
            { value: "v60_Cross_Country", label: "V60 Cross Country" },
            { value: "v70", label: "V70" },
            { value: "v90", label: "V90" },
            { value: "v90_Cross_Country", label: "V90 Cross Country" },
            { value: "xc40", label: "XC40" },
            { value: "xc60", label: "XC60" },
            { value: "xc70", label: "XC70" },
            { value: "xc90", label: "XC90" },
        ],
        other: [
            { value: "other", label: "Other" },
        ],
    }
}
// export const services = [
//     { value: 'trail-hitcher', label: 'Trail Hitcher', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
//     { value: 'body-cover', label: 'Body Cover', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
//     { value: 'patriot-liner', label: 'Patriot Liner', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
//     { value: 'suspension', label: 'Suspension', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
//     { value: 'rust-prevention', label: 'Rust Prevention', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
//     { value: 'ceramic-coating', label: 'Ceramic Coating', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
//     { value: 'service7', label: 'Service7', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
//     { value: 'service8', label: 'Service8', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
//     { value: 'service9', label: 'Service9', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
//     { value: 'service10', label: 'Service10', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
//     { value: 'service11', label: 'Service11', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
//     { value: 'service12', label: 'Service12', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
// ];

export const services = [
    { value: 'trailerHitch', label: 'Trailer Hitch', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'bedCover', label: 'Bed Cover', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'patriotLiner', label: 'Patriot Liner', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'suspension', label: 'Suspension', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'rustPrevention', label: 'Rust Prevention', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'ceramicCoating', label: 'Ceramic Coating', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'ppf', label: 'PPF (Clear Bra)', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'detailing', label: 'Detailing', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'vanPackages', label: 'Van Packages', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'fleetManagement', label: 'Fleet Management', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
    { value: 'otherService', label: 'Other Service', tooltipDesc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt molestias facilis praesentium vitae consectetur nemo dolorum facere quas qui ducimus eius earum.", "Lorem ipsum dolor sit amet consectetur adipisicing elite."] },
];