export const servicesData = [
    {
        id: 1,
        imageSrc: '/services/service1.png',
        serviceName: 'Patriot Liner',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 2,
        imageSrc: '/services/service2.png',
        serviceName: 'Waxoyl Undercoating ',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 3,
        imageSrc: '/services/service3.png',
        serviceName: 'Ceramic Coatings',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 4,
        imageSrc: '/services/service4.png',
        serviceName: 'CPC Anti-Corrosion Graphene Clear Coat',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 5,
        imageSrc: '/services/service5.png',
        serviceName: 'Window Tint',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 6,
        imageSrc: '/services/service6.png',
        serviceName: 'Hitches',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 7,
        imageSrc: '/services/service7.png',
        serviceName: 'Wheels & Tires',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 8,
        imageSrc: '/services/service3.png',
        serviceName: 'Ceramic Coatings',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 9,
        imageSrc: '/services/service2.png',
        serviceName: 'Waxoyl Undercoating ',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 10,
        imageSrc: '/services/service1.png',
        serviceName: 'Patriot Liner',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 11,
        imageSrc: '/services/service7.png',
        serviceName: 'Wheels & Tires',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 12,
        imageSrc: '/services/service6.png',
        serviceName: 'Hitches',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 13,
        imageSrc: '/services/service5.png',
        serviceName: 'Window Tint',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 14,
        imageSrc: '/services/service4.png',
        serviceName: 'CPC Anti-Corrosion Graphene Clear Coat',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 15,
        imageSrc: '/services/service1.png',
        serviceName: 'Patriot Liner',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 16,
        imageSrc: '/services/service2.png',
        serviceName: 'Waxoyl Undercoating ',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 17,
        imageSrc: '/services/service3.png',
        serviceName: 'Ceramic Coatings',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 18,
        imageSrc: '/services/service4.png',
        serviceName: 'CPC Anti-Corrosion Graphene Clear Coat',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 19,
        imageSrc: '/services/service5.png',
        serviceName: 'Window Tint',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 20,
        imageSrc: '/services/service6.png',
        serviceName: 'Hitches',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
    {
        id: 21,
        imageSrc: '/services/service7.png',
        serviceName: 'Wheels & Tires',
        serviceDesc: 'Welcome to Capital Upfitters, the family-owned epicenter of top-tier. ',
    },
]